/**
    @file MasterData_Trap.cs
    @brief MasterData_Trap Schema
    @note This file is automatically generated. Do not edit manually.
*/

using System;

namespace MasterData.Schema
{

	[Serializable]
	public class TrapsData
	{
		public int ID { get; set; }
		public int ContentID { get; set; }
		public string Name { get; set; } = string.Empty;
		public int Kind { get; set; }
		public int Cost { get; set; }
		public int ParameterID { get; set; }
		public string ResourceID { get; set; } = string.Empty;
		public string IconResourceID { get; set; } = string.Empty;
		public int IsBlock { get; set; }
		public int IsRotate { get; set; }
		public int IsContinuable { get; set; }
		public int TriggerKind { get; set; }
	}

	[Serializable]
	public class TrapsParameterData
	{
		public int ID { get; set; }
		public int Damage { get; set; }
		public int CoolTime { get; set; }
		public int RangeKind { get; set; }
		public int Range { get; set; }
		public int SearchRangeKind { get; set; }
		public int SearchRange { get; set; }
		public int KnockbackKind { get; set; }
		public int KnockbackPower { get; set; }
	}
}
