/**
    @file MasterData_Placement.cs
    @brief MasterData_Placement Schema
    @note This file is automatically generated. Do not edit manually.
*/

using System;

namespace MasterData.Schema
{

	[Serializable]
	public class StageData
	{
		public int ID { get; set; }
		public int ContentID { get; set; }
		public string Name { get; set; } = string.Empty;
		public int Wave { get; set; }
		public int PoolGroupID { get; set; }
		public long Gold { get; set; }
		public int Exp { get; set; }
	}

	[Serializable]
	public class WaveEnemyGroupData
	{
		public int ID { get; set; }
		public int GroupID { get; set; }
		public int EnemyID { get; set; }
		public int Count { get; set; }
		public int Interval { get; set; }
	}

	[Serializable]
	public class StageWavePoolData
	{
		public int ID { get; set; }
		public int GroupID { get; set; }
		public int WaveMin { get; set; }
		public int WaveMax { get; set; }
		public int EnemyGroupID { get; set; }
		public int Weight { get; set; }
		public int SpawnPositionID { get; set; }
	}
}
