/**
    @file MasterDataSchemas.cs
    @brief MasterDataSchemas
    @note This file is automatically generated. Do not edit manually.
*/

using MasterData.Schema;

public class MasterDataSchemas
{
    public FixData[] Fix { get; set; } = null!;
    public FixValueGroupData[] FixValueGroup { get; set; } = null!;
    public TrapsData[] Traps { get; set; } = null!;
    public TrapsParameterData[] TrapsParameter { get; set; } = null!;
    public EnemiesData[] Enemies { get; set; } = null!;
    public EnemiesParameterData[] EnemiesParameter { get; set; } = null!;
    public StageData[] Stage { get; set; } = null!;
    public WaveEnemyGroupData[] WaveEnemyGroup { get; set; } = null!;
    public StageWavePoolData[] StageWavePool { get; set; } = null!;

}