/**
    @file MasterData_Enemy.cs
    @brief MasterData_Enemy Schema
    @note This file is automatically generated. Do not edit manually.
*/

using System;

namespace MasterData.Schema
{

	[Serializable]
	public class EnemiesData
	{
		public int ID { get; set; }
		public int ContentID { get; set; }
		public string Name { get; set; } = string.Empty;
		public string ResourceID { get; set; } = string.Empty;
		public int ParameterID { get; set; }
		public int RaceKind { get; set; }
	}

	[Serializable]
	public class EnemiesParameterData
	{
		public int ID { get; set; }
		public int HP { get; set; }
		public int Attack { get; set; }
		public int Speed { get; set; }
	}
}
