/**
    @file MasterData_Common.cs
    @brief MasterData_Common Schema
    @note This file is automatically generated. Do not edit manually.
*/

using System;

namespace MasterData.Schema
{

	[Serializable]
	public class FixData
	{
		public int ID { get; set; }
		public string Key { get; set; } = string.Empty;
		public string Kind { get; set; } = string.Empty;
		public int Ref_Group { get; set; }
	}

	[Serializable]
	public class FixValueGroupData
	{
		public int ID { get; set; }
		public int GroupID { get; set; }
		public string Value { get; set; } = string.Empty;
	}
}
