/**
    @file MasterDataEfEntityGenerator.cs
    @brief ASP.NET / EF Core 向け Entity を生成する
*/

using System.Text;
using static MasterDataConverter.GoogleSpreadSheetService;

namespace MasterDataConverter;

/// <summary>
/// スキーマ定義から EF Core Entity と GameDbContext 用の DbSet を生成する
/// </summary>
public static class MasterDataEfEntityGenerator
{
    const string EntityNamespace = "MasterData.Entities";
    const string DbContextClassName = "GameDbContext";
    const string DbContextFileName = "GameDbContext.MasterData.cs";
    const string SchemaClassName = "MasterDataSchema";
    const string SchemaFileName = "MasterDataSchema.cs";

    /// <summary>
    /// 全マスターのスキーマから Entity・GameDbContext 用 DbSet・MasterDataSchema を出力する
    /// </summary>
    /// <param name="outputDir">サーバー向け出力ディレクトリ</param>
    /// <param name="schemaByMaster">マスター名 → シート名 → カラム定義</param>
    public static void Generate(
        string outputDir,
        Dictionary<string, Dictionary<string, List<MasterSchemaEntity>>> schemaByMaster)
    {
        Directory.CreateDirectory(outputDir);

        var entities = FlattenSchemas(schemaByMaster);
        foreach (var entity in entities)
        {
            var filePath = Path.Combine(outputDir, $"{entity.ClassName}.cs");
            File.WriteAllText(filePath, BuildEntitySource(entity));
            Console.WriteLine($"  EF Entity Exported: {Path.GetFullPath(filePath)}");
        }

        var dbContextPath = Path.Combine(outputDir, DbContextFileName);
        File.WriteAllText(dbContextPath, BuildDbContextSource(entities));
        Console.WriteLine($"  EF DbContext Partial Exported: {Path.GetFullPath(dbContextPath)}");

        var schemaPath = Path.Combine(outputDir, SchemaFileName);
        File.WriteAllText(schemaPath, BuildMasterDataSchemaSource(entities));
        Console.WriteLine($"  MasterDataSchema Exported: {Path.GetFullPath(schemaPath)}");
    }

    /// <summary>
    /// マスター単位のスキーマをシート単位の Entity 定義へ平坦化する
    /// </summary>
    /// <param name="schemaByMaster">マスター名 → シート名 → カラム定義</param>
    /// <returns>重複シート名を除いた Entity 定義一覧</returns>
    static List<EntityDefinition> FlattenSchemas(
        Dictionary<string, Dictionary<string, List<MasterSchemaEntity>>> schemaByMaster)
    {
        var result = new List<EntityDefinition>();
        var usedClassNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var (masterName, schemaBySheet) in schemaByMaster)
        {
            foreach (var (sheetName, schemas) in schemaBySheet)
            {
                var tableName = SanitizeIdentifier(sheetName);
                if (string.IsNullOrEmpty(tableName) || schemas.Count == 0)
                {
                    continue;
                }

                if (usedClassNames.Add(tableName) == false)
                {
                    Console.WriteLine($"  Warning: Duplicate sheet name '{sheetName}' in {masterName} was skipped.");
                    continue;
                }

                result.Add(new EntityDefinition
                {
                    ClassName = tableName,
                    TableName = tableName,
                    JsonKey = sheetName.Trim().Trim('\'', '"'),
                    Columns = schemas
                        .Where(schema => string.IsNullOrWhiteSpace(schema.ColumnName) == false)
                        .ToList(),
                });
            }
        }

        return result;
    }

    /// <summary>
    /// 1 Entity 分の C# ソースを組み立てる
    /// </summary>
    /// <param name="entity">出力対象の Entity 定義</param>
    /// <returns>生成ソース</returns>
    static string BuildEntitySource(EntityDefinition entity)
    {
        var sb = new StringBuilder();

        sb.AppendLine("/**");
        sb.AppendLine($"    @file {entity.ClassName}.cs");
        sb.AppendLine($"    @brief {entity.ClassName} EF Entity");
        sb.AppendLine("    @note This file is automatically generated. Do not edit manually.");
        sb.AppendLine("*/");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        sb.AppendLine();
        sb.AppendLine($"namespace {EntityNamespace}");
        sb.AppendLine("{");
        sb.AppendLine();
        sb.AppendLine($"\t[Table(\"{entity.TableName}\")]");
        sb.AppendLine($"\tpublic partial class {entity.ClassName}");
        sb.AppendLine("\t{");

        foreach (var column in entity.Columns)
        {
            var propertyName = SanitizeIdentifier(column.ColumnName);
            var clrType = MapClrType(column.ValueType);
            var isPrimaryKey = IsPrimaryKey(column.ColumnName);

            if (isPrimaryKey)
            {
                sb.AppendLine("\t\t[Key]");
                sb.AppendLine("\t\t[DatabaseGenerated(DatabaseGeneratedOption.None)]");
            }

            sb.AppendLine($"\t\t[Column(\"{column.ColumnName}\")]");
            sb.AppendLine($"\t\tpublic {clrType} {propertyName} {{ get; set; }}{MapPropertyInitializer(clrType)}");
            sb.AppendLine();
        }

        sb.AppendLine("\t}");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// 既存の GameDbContext へ結合する、マスター用 DbSet の partial ソースを組み立てる
    /// </summary>
    /// <param name="entities">出力済み Entity 定義</param>
    /// <returns>生成ソース</returns>
    static string BuildDbContextSource(List<EntityDefinition> entities)
    {
        var sb = new StringBuilder();

        sb.AppendLine("/**");
        sb.AppendLine($"    @file {DbContextFileName}");
        sb.AppendLine($"    @brief {DbContextClassName} のマスターデータ DbSet");
        sb.AppendLine("    @note This file is automatically generated. Do not edit manually.");
        sb.AppendLine("*/");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine($"namespace {EntityNamespace}");
        sb.AppendLine("{");
        sb.AppendLine();
        sb.AppendLine($"\tpublic partial class {DbContextClassName}");
        sb.AppendLine("\t{");

        foreach (var entity in entities)
        {
            sb.AppendLine($"\t\tpublic DbSet<{entity.ClassName}> {entity.ClassName} => Set<{entity.ClassName}>();");
        }

        sb.AppendLine("\t}");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// JSON をまとめてデシリアライズするための MasterDataSchema ソースを組み立てる
    /// </summary>
    /// <param name="entities">出力済み Entity 定義</param>
    /// <returns>生成ソース</returns>
    static string BuildMasterDataSchemaSource(List<EntityDefinition> entities)
    {
        var sb = new StringBuilder();

        sb.AppendLine("/**");
        sb.AppendLine($"    @file {SchemaFileName}");
        sb.AppendLine("    @brief マスターデータ JSON のルートクラス");
        sb.AppendLine("    @note This file is automatically generated. Do not edit manually.");
        sb.AppendLine("*/");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {EntityNamespace}");
        sb.AppendLine("{");
        sb.AppendLine();
        sb.AppendLine($"\tpublic partial class {SchemaClassName}");
        sb.AppendLine("\t{");

        foreach (var entity in entities)
        {
            sb.AppendLine($"\t\t[JsonPropertyName(\"{entity.JsonKey}\")]");
            sb.AppendLine($"\t\tpublic {entity.ClassName}[] {entity.ClassName} {{ get; set; }} = null!;");
            sb.AppendLine();
        }

        sb.AppendLine("\t}");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// スプレッドシートの型名を CLR 型へ変換する
    /// </summary>
    /// <param name="valueType">スプレッドシート上の型名</param>
    /// <returns>C# の型名</returns>
    static string MapClrType(string valueType)
    {
        var normalized = valueType.Trim();

        return normalized.ToLowerInvariant() switch
        {
            "int" or "integer" or "int32" => "int",
            "long" or "int64" => "long",
            "float" => "float",
            "double" or "number" or "real" => "double",
            "bool" or "boolean" => "bool",
            "bigdouble" => "string",
            _ => string.IsNullOrEmpty(normalized) ? "string" : normalized,
        };
    }

    /// <summary>
    /// 参照型プロパティの初期化子を返す
    /// </summary>
    /// <param name="clrType">CLR 型名</param>
    /// <returns>初期化子。値型は空文字</returns>
    static string MapPropertyInitializer(string clrType)
    {
        return clrType == "string" ? " = string.Empty;" : string.Empty;
    }

    /// <summary>
    /// 主キー列かどうかを判定する
    /// </summary>
    /// <param name="columnName">カラム名</param>
    /// <returns>ID 列なら true</returns>
    static bool IsPrimaryKey(string columnName)
    {
        return string.Equals(columnName, "ID", StringComparison.Ordinal);
    }

    /// <summary>
    /// クラス名・プロパティ名として使える識別子に整形する
    /// </summary>
    /// <param name="name">元の名前</param>
    /// <returns>サニタイズ済み識別子</returns>
    static string SanitizeIdentifier(string name)
    {
        var trimmed = name.Trim().Trim('\'', '"');
        var chars = trimmed
            .Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_')
            .ToArray();

        var sanitized = new string(chars);
        if (string.IsNullOrEmpty(sanitized) || char.IsDigit(sanitized[0]))
        {
            sanitized = $"_{sanitized}";
        }

        return sanitized;
    }

    /// <summary>
    /// 生成対象の Entity 定義
    /// </summary>
    sealed class EntityDefinition
    {
        public string ClassName { get; set; } = string.Empty;
        public string TableName { get; set; } = string.Empty;
        public string JsonKey { get; set; } = string.Empty;
        public List<MasterSchemaEntity> Columns { get; set; } = [];
    }
}
