/**
    @file MasterDataCodeGenerator.cs
    @brief スキーマをもとにコードを生成する
*/

using System.Text;

namespace MasterDataConverter;

public static class MasterDataCodeGenerator
{
    public static void GenerateCode(string outputDir, Dictionary<string, List<GoogleSpreadSheetService.MasterSchemaEntity>> schemaBySheet, string masterName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("/**");
        sb.AppendLine($"    @file {masterName}.cs");
        sb.AppendLine($"    @brief {masterName} Schema");
        sb.AppendLine($"    @note This file is automatically generated. Do not edit manually.");
        sb.AppendLine("*/");
        sb.AppendLine();
        sb.AppendLine($"using System;");
        if (IsExistBigDouble(schemaBySheet))
        {
            sb.AppendLine("using BreakInfinity;");
        }
        sb.AppendLine();
        sb.AppendLine("namespace MasterData.Schema");
        sb.AppendLine("{");

        foreach (var kvp in schemaBySheet)
        {
            sb.AppendLine();
            sb.AppendLine($"\t[Serializable]");
            sb.AppendLine($"\tpublic class {kvp.Key}Data");
            sb.AppendLine("\t{");
            foreach (var schema in kvp.Value)
            {
                sb.AppendLine($"\t\tpublic {schema.ValueType} {schema.ColumnName} {{ get; set; }}");
            }
            sb.AppendLine("\t}");
        }
        sb.AppendLine("}");

        File.WriteAllText(Path.Combine(outputDir, $"{masterName}.cs"), sb.ToString());
    }


    /// <summary>
    /// Dictionaryの情報を元にenum用の文字列を作成する
    /// </summary>
    /// <param name="outputDir"></param>
    /// <param name="fileName"></param>
    /// <param name="datas"></param>
    /// <returns></returns>
    public static void CreateEnumString(string outputDir, string fileName,Dictionary<string, Dictionary<string, object>> datas)
    {
        var sb = new StringBuilder();

        sb.AppendLine("/**");
        sb.AppendLine($"    @file {fileName}.cs");
        sb.AppendLine($"    @brief Enum Definition");
        sb.AppendLine($"    @note This file is automatically generated. Do not edit manually.");
        sb.AppendLine("*/");
        sb.AppendLine();

        sb.AppendLine("namespace MasterData.Schema");
        sb.AppendLine("{");

        foreach (var kvp in datas)
        {
            sb.AppendLine($"\tpublic enum {kvp.Key}");
            sb.AppendLine("\t{");
            foreach (var kvp1 in datas[kvp.Key])
            {
                if (kvp1.Value is Dictionary<string, object> dic)
                {
                    sb.AppendLine($"\t\t{kvp1.Key}\t=\t{dic["value"]},\t\t//{dic["display"]}");
                }
            }
            sb.AppendLine("\t}\n");
        }
        sb.AppendLine("}");

        File.WriteAllText(Path.Combine(outputDir, $"{fileName}.cs"), sb.ToString());
    }

    /// <summary>
    /// BigDoubleが存在するかどうかを判断する
    /// </summary>
    /// <param name="schemaBySheet"></param>
    /// <returns></returns>
    public static bool IsExistBigDouble(Dictionary<string, List<GoogleSpreadSheetService.MasterSchemaEntity>> schemaBySheet)
    {
        foreach (var kvp in schemaBySheet)
        {
            foreach (var schema in kvp.Value)
            {
                if (schema.ValueType == "BigDouble")
                {
                    return true;
                }
            }
        }

        return false;
    }
    
}
